[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 800

fs_permissions = [
    { access = "read", path = "test/Data" },
    { access = "read", path = "test/Data/" },
    { access = "read", path = "./test/Data" },
    { access = "read", path = "./test/Data/" },
    { access = "write", path = "test/Output" },
    { access = "write", path = "test/Output/" },
    { access = "write", path = "./test/Output" },
    { access = "write", path = "./test/Output/" }
]

[fmt]
line_length = 100

gas_snapshot_check = true